#!/bin/bash

# Shell script to prepare a VM for batch at interactive time

EXEC_NAME=$(basename $0 .${0##*.})
EXEC_VERSION=0.1.1

msg() {
    echo " >> ${EXEC_NAME}: $1"
}

die() {
    echo "${EXEC_NAME} Error: $1" 1>&2
    exit 1
}

usage() {
    echo $"Usage: ${EXEC_NAME}
Prepare a VM for batch on CANFAR:
1. Setup a workspace on an ephemeral partition to work on while interactive (/mnt/work)
2. Install condor if VM is either RPM or DEB based.
"
    exit
}

canfar_install_condor_rpm() {
    msg "rpm/yum based distribution detected"
    local rh_vers=$(rpm -qa \*-release | grep -Ei "redhat|centos|sl" | cut -d "-" -f3)
    if [[ -n ${rh_vers} ]]; then
	msg "distribution version ${rh_vers} detected, adding condor yum repo"
	rpm --import https://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
	curl -sL https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel${rh_vers}.repo \
	     -o /etc/yum.repos.d/htcondor-stable-rhel${rh_vers}.repo
    else
	msg "non-RHEL distribution, assuming condor is already available from current repos"
    fi
    yum -y install condor || die "failed to install condor"
    # on CentOS 7 /var/lock/condor is incorrectly owned by root
    if condor_version | grep -q RedHat_7; then
        msg "RedHat 7 derivatives need hack for /var/lock/condor ownership."
        mkdir -p /var/lock/condor
        chown condor:condor /var/lock/condor
    fi
}

canfar_install_condor_deb() {
    msg "apt/dpkg distribution detected assume debian wheezy"
    export DEBIAN_FRONTEND=noninteractive
    local condordeb="deb http://research.cs.wisc.edu/htcondor/debian/stable/ wheezy contrib"
    if [[ -d /etc/apt/sources.list.d ]]; then
	echo "${condordeb}" > /etc/apt/sources.list.d/condor.list
    else
	echo "${condordeb}" >> /etc/apt/sources.list
    fi
    wget -qO - http://research.cs.wisc.edu/htcondor/debian/HTCondor-Release.gpg.key | apt-key add - > /dev/null
    apt-get -q update -y
    msg "installing condor..."
    # htcondor is the name of the package in debian repo, condor is the name in the condor repo
    apt-get -q install -y condor || die "condor didn't install properly"
}


# install condor for rpm or deb distros
# avoid ruby bloat and new language to learn from puppet/chef
canfar_install_condor() {
    local cv=$(condor_version 2> /dev/null | awk '/BuildID/ {print $2}')
    # 8.4.5 has a critical bug that does not work with dynamic slots
    [[ -n ${cv} ]] && [[ ${cv} != 8.4.5 ]] && msg "condor is already installed" && return 0
    msg "installing/updating condor"
    # determine os
    if yum --version > /dev/null 2>&1 ; then
	canfar_install_condor_rpm
    elif apt-get --version > /dev/null 2>&1 ; then
	canfar_install_condor_deb
    else
	die "unable to detect distribution type, you must install it yourself"
    fi
}

canfar_setup_workdir() {
    local ephemdir="/mnt"
    local workdir="${ephemdir}/work"

    msg "setting up working ephemeral directory on ${workdir}"
    if ! mount | grep -q ${ephemdir}; then 
	msg "ephemeral partition not mounted trying"
	mkdir -p ${ephemdir}
	mount /dev/vdb ${ephemdir} || \
	    die "Not a VM with ephemeral partition. Terminate and choose another flavor"
    fi    
    mkdir -p ${workdir}
    chmod 777 ${workdir}
}

# Store all options
OPTS=$(getopt \
    -o hv \
    -l help \
    -l version \
    -- "$@")

eval set -- "${OPTS}"

# Process options
while true; do
    case "$1" in
	-h | --help) usage ;;
	-V | --version) echo ${EXEC_VERSION}; exit ;;
	--)  shift; break ;; # no more options
	*) break ;; # parameters
    esac
    shift
done

export PATH="/sbin:/usr/sbin:${PATH}"
canfar_setup_workdir
canfar_install_condor
