#!/bin/bash
#
# User script for submitting jobs. A wrapper for canfar_vm_share and
# condor_submit.

EXEC_NAME=$(basename $0 .${0##*.})

die() {
    echo "${EXEC_NAME}: $1" 1>&2
    exit 1
}

usage() {
    echo $"Usage: ${EXEC_NAME} [jobfile] [arg1] [arg2] ... [argn]
Submit a CANFAR processing job
  [jobfile]           CANFAR job submission file
  [arg1] ... [argn]   Additional parameters passed to condor_submit
"
    exit
}


[ "$#" -ge 1 ] || usage

JOBFILE=$1

[[ ! -e ${JOBFILE} ]] && die "jobfile '${JOBFILE}' does not exist"

canfar_vm_share ${JOBFILE} || die "failed to share VM with batch tenant"

condor_submit "$@" || die "failed to submit job to queue"
