#!/bin/bash
#
# User script for submitting jobs. A wrapper for canfar_job_validate and
# condor_submit.

EXEC_NAME=$(basename $0 .${0##*.})

die() {
    echo "${EXEC_NAME}: $1" 1>&2
    exit 1
}

usage() {
    echo $"Usage: ${EXEC_NAME} [jobfile] [image_uri] [flavor]
Submit a CANFAR processing job
  [jobfile]           Condor job submission file
  [image_uri]         VM image for job, can be 'canfar:image_uuid' or 'canfar:tenant_name/image_name'
  [flavor]            A valid hardware flavor
"
    exit
}


[ "$#" -eq 3 ] || usage

JOBFILE=$1
IMAGE_URI=$2
FLAVOR=$3

[[ -e ${JOBFILE} ]] || die "jobfile '${JOBFILE}' does not exist"

JOB=`canfar_job_validate ${JOBFILE} ${IMAGE_URI} ${FLAVOR}` || die "failed to validate jobfile: ${JOB}"

echo ${JOB} | condor_submit || die "failed to submit job to queue"
