#!/usr/bin/env python
#
# Generate multi-part mime file to configure batch VM on startup

import sys

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Note that cloud-init seems to execute these in reverse order
inputfiles = [ 'cloud_scheduler_setup.bash:text/x-shellscript',
               'cloud_scheduler_cloud_config.yml:text/cloud-config' ]

combined_message = MIMEMultipart()
for i in inputfiles:
    (filename, format_type) = i.split(":", 1)
    with open(filename) as fh:
        contents = fh.read()
    sub_message = MIMEText(contents, format_type, sys.getdefaultencoding())
    sub_message.add_header('Content-Disposition', 'attachment; filename="%s"' % (filename))
    combined_message.attach(sub_message)

print(combined_message)
